### ISSUE TITLE
Have you written something regarding using your work on a different dataset ?

### ISSUE THREAD

**Issue by valentindjangone** [Altaheri/EEG-ATCNet#11]
I'm trying to classify 4 classes, motor movements. I would like to try using your work but I have issues with knowing what I have to use and what I can afford to leave on the side in your code.
By any chance, do you have written something that would help guide me through using your work on my dataset ?

**Comment by Altaheri** [comment]
Change the following line that loads the dataset with your own dataset:

```
        # Get training and test data
        X_train, _, y_train_onehot, X_test, _, y_test_onehot = get_data(
            data_path, sub, LOSO, isStandard)
```

Your data should has: #classes = 4, #chans = 22, and #samples = 1125. Or you can change the values of these parameters in the `def getModel(model_name):` function

**Comment by valentindjangone** [comment]
Thank you! I will give it a try.
