### ISSUE TITLE
LOSO : True

### ISSUE THREAD

**Issue by p1x31** [Altaheri/EEG-ATCNet#14]
When setting LOSO : True in dataset_conf dictionary im getting error:
line 64, in load_data_LOSO
    elif (X_train == []):
ValueError: operands could not be broadcast together with shapes (576,22,1750) (0,)

tf version 2.14.0

Am I missing something?

**Comment by Altaheri** [comment]
Hello, the code has been updated, you can try the new update.

**Comment by Altaheri** [comment]
![image](https://github.com/user-attachments/assets/1c4b1edb-bd1f-4bba-91c0-719eb60ffb37)
