### ISSUE TITLE
Update of dynamic convolution module and multi-level attention module

### ISSUE THREAD

**Issue by mediatehuang** [Altaheri/EEG-ATCNet#18]
Hello, recently read the article of multi-level attention dynamic convolution based on EEG moving image decoding, may I ask if this article has open source code? I read your article and benefited a lot. I hope to combine your dynamic convolution module with your multi-level focus module. I would appreciate it if you have open source to learn. With all my best wishes

**Comment by Altaheri** [comment]
Hi @mediatehuang 

In our implementation of dynamic convolution, we used code from our previous work ([ATCNet](https://doi.org/10.1109/TII.2022.3197419)) and modified it to include multilevel attention and dynamic convolution blocks, replacing standard convolution blocks with dynamic ones. You can add these modifications to the original ATCNet model.

For the dynamic convolution, we adapted the implementation from this source: https://github.com/prstrive/CondConv-tensorflow. However, please note that this dynamic convolution implementation is inefficient, and we need to refine it before making the code publicly available.
