### ISSUE TITLE
Error

### ISSUE THREAD

**Issue by gfm360733** [Altaheri/EEG-ATCNet#19]
Hello, there is a problem with the code and it doesn't work. This code in the data preprocessing file reports an error:
  if training:
        a = sio.loadmat(data_path+'A0'+str(subject)+'T.mat')

    else:
        a = sio.loadmat(data_path+'A0'+str(subject)+'E.mat')
    a_data = a['data']

Error: a_data = a['data']
KeyError: 'data'

Please tell me how to solve it? Thanks
![369988cfd6b6e1d61b10b3c0beddd9f](https://github.com/user-attachments/assets/e274161a-17c9-450f-9b05-db7800585b4f)

**Comment by gfm360733** [comment]
Totally wrong code, when will the author improve the code? Once you post the article, you don’t care? I suggest you cancel this project code.

**Comment by gfm360733** [comment]
浪费时间

**Comment by gfm360733** [comment]
~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~

**Comment by Altaheri** [comment]
Hi @gfm360733,

There is no issue with the code itself. The problem might be related to an incorrect file path. Please ensure that you're using the correct path and that the dataset files are located in the expected directories. A small typo or mistake in the file path could cause the loadmat() function to fail in finding the necessary data.

Additionally, please double-check that the file actually exists at the specified path. You can use the following code to confirm whether the file is present:
```
import os
print(os.path.exists(data_path+'A0'+str(subject)+'E.mat'))

```
To help further troubleshoot, you can also run the following command to inspect the contents of the .mat file:

```
a = sio.loadmat(data_path+'A0'+str(subject)+'E.mat')
print(a.keys())

```
This will allow you to confirm whether the 'data' key exists and if the file structure is as expected.

**Comment by Kingward1017** [comment]
Hello@Altaheri
I ran the command to see the key value 
print(a.keys())
 and got the following output：
dict_keys(['__header__', '__version__', '__globals__', 'h', 's'])
Which of these is most likely to correspond to 'data'?
Thanks a lot!!!

**Comment by Altaheri** [comment]
@Kingward1017 the output of the following:
```
a = sio.loadmat(data_path+'A0'+str(subject)+'T.mat')
print(a.keys()) 
```
should be like:
`dict_keys(['__header__', '__version__', '__globals__', 'data'])`

dounload the BCI Competition IV-2a form the following link: [BCI Competition IV-2a](https://www.bbci.de/competition/iv/#dataset2a): https://bnci-horizon-2020.eu/database/data-sets

**Comment by gfm360733** [comment]
> Hi @gfm360733,
> 
> There is no issue with the code itself. The problem might be related to an incorrect file path. Please ensure that you're using the correct path and that the dataset files are located in the expected directories. A small typo or mistake in the file path could cause the loadmat() function to fail in finding the necessary data.↳
> 
> Additionally, please double-check that the file actually exists at the specified path. You can use the following code to confirm whether the file is present:↳
> 
> ```
> import os
> print(os.path.exists(data_path+'A0'+str(subject)+'T.mat'))
> print(os.path.exists(data_path+'A0'+str(subject)+'E.mat'))
> ```
> 
> To help further troubleshoot, you can also run the following command to inspect the contents of the .mat file:↳
> 
> ```
> a = sio.loadmat(data_path+'A0'+str(subject)+'T.mat')
> print(a.keys())
> ```
> 
> This will allow you to confirm whether the 'data' key exists and if the file structure is as expected.↳

Problem solved, thank you very much

**Comment by gfm360733** [comment]
@Altaheri ok，the Problem solved, thank you very much
