### ISSUE TITLE
About the shape of Wo in equation (12).

### ISSUE THREAD

**Issue by musicrainie** [Altaheri/EEG-ATCNet#20]
Thanks for your gorgeous work.
Shouldn't it be (dH * H, d) according to the concatenation?

**Comment by Altaheri** [comment]
Hi @musicrainie, This is a good question,

As noted, there was a minor typo in the equation 12. The dimensionality of the projection matrix Wo should be (H*dH × d) not (dH × d). Here, H is the number of heads, dH is the dimensionality of each head. This ensures that the output of the multi-head attention operation has the same dimensionality as its input, maintaining consistency throughout the model.

The detailed explanation is as follows:

![image](https://github.com/user-attachments/assets/4c66f11d-1452-4e43-8953-125c60cab636)
