### ISSUE TITLE
Question about the size of input data

### ISSUE THREAD

**Issue by comojin1994** [Altaheri/EEG-ATCNet#3]
Hi,

I read your paper. I'm really impressive your method.

However, I have a question about your data size.
In your paper, the temporal size of input data is 1125.
The sampling rate of the dataset is 250 Hz, and, based on the dataset description, the time for conducting the task is four sec., including cue time.

![Screen Shot 2022-09-01 at 3 59 22 PM](https://user-images.githubusercontent.com/46745325/187851784-7bbbddb0-f187-42a5-966e-95fee7932bad.png)

I think 1125 (temporal size of input data) was calculated by 250 * 4.5 sec..

![Screen Shot 2022-09-01 at 4 01 57 PM](https://user-images.githubusercontent.com/46745325/187852266-1babd239-d992-4fda-8d63-04689c4eaed3.png)

So, why did you set the task to 4.5 seconds?

**Comment by Altaheri** [comment]
Hi, thank you,
In the BCI-C 4-2a dataset, motor image tasks were performed starting at second “2” and lasting four seconds (up to second “6”). In our experiments, we cut the trial 4 s and 500 ms before the trial (from 1.5 to 6). It is useful to cut off a period ( e.g., 500 ms) before the trial.

**Comment by comojin1994** [comment]
@Altaheri 

Thank you for your response.

But I still have a question about your explanation.

As shown upper figure of the paradigm, the cue starts at 2 sec, and imagination starts at 3 sec.

So, why did you think that motor imagery tasks start at 2 sec.? I cannot find the description of this on the official description page.

**Comment by Altaheri** [comment]
That is mentioned in the official dataset document, as follows:

_"After two seconds (t = 2 s), a cue in the form of an arrow pointing either to the left, right, down or up (corresponding to one of the four classes left hand, right hand, foot or tongue) appeared and stayed on the screen for 1.25 s. _**This prompted the subjects to perform the desired motor imagery task.**_"_

[BCI Competition IV 2a description_2.pdf](https://github.com/Altaheri/EEG-ATCNet/files/9526107/BCI.Competition.IV.2a.description_2.pdf)

**Comment by comojin1994** [comment]
@Altaheri 

Thank you for your kind response.

It was really helpful to me.
