### ISSUE TITLE
I want to add a program

### ISSUE THREAD

**Issue by hljuniversity** [Altaheri/EEG-ATCNet#5]
Hello, thank you for sharing the code，I added a piece of de-noising code to the ATCNet model, which reduced the accuracy of the verification set. I don't understand why. Do you understand?

**Comment by Altaheri** [comment]
Hi, It depends on which method you used. Some key features may be lost during the denoising process. In deep learning (DL), noise may not be an issue. DL can learn very well from noisy data. Also, adding noise to the EEG data is one way to augment the data and help the model to generalize well. I haven't worked with noise removal in the EEG data; However, you may refer to the following review article which discusses the effect of pre-processing on MI-EEG data (including denoising) for DL-based techniques.  

https://link.springer.com/article/10.1007/s00521-021-06352-5

**Comment by hljuniversity** [comment]
> Hi, It depends on which method you used. Some key features may be lost during the denoising process. In deep learning (DL), noise may not be an issue. DL can learn very well from noisy data. Also, adding noise to the EEG data is one way to augment the data and help the model to generalize well. I haven't worked with noise removal in the EEG data; However, you may refer to the following review article which discusses the effect of pre-processing on MI-EEG data (including denoising) for DL-based techniques.
> 
> https://link.springer.com/article/10.1007/s00521-021-06352-5

I'm glad to receive your reply. I want to change your program, but I don't know how to start. I want to try to de-noise first. Can you give me some suggestions? Thank you very much.
