### ISSUE TITLE
Dataset download

### ISSUE THREAD

**Issue by NgHanWei** [Altaheri/EEG-ATCNet#9]
Hello, the dataset download from the provided link does not seem to be working. Is there any alternative for us to download the .mat dataset from? Thanks in advance.

**Comment by Altaheri** [comment]
Hi, yes the links don't seem to work now but the original dataset can be downloaded from the following link (in GDF format):

https://www.bbci.de/competition/iv/download/index.html?agree=yes&submit=Submit

**Comment by NgHanWei** [comment]
Thanks for the response, the gdf files won't work because the evaluation set lacks the annotation, I've contacted the relevant person for the links so hopefully it will be up again soon.

**Comment by Altaheri** [comment]
You can try now, the links are working.

**Comment by NgHanWei** [comment]
Yes it works now, thank you.
